version: '3.8'

services:

  dashboard-fpm:
    container_name: fpm

    build:
      context: .
      dockerfile: Dockerfile_dashboard-fpm

    networks:
      - dashboard

    volumes:
      - ./fpm:/var/www/html/

    ports:
      - "9000:9000"

  dashboard-host:
    container_name: host

    build:
      context: .
      dockerfile: Dockerfile_dashboard-host

    networks:
      - dashboard

    volumes:
      - ./fpm/:/var/www/html/

    ports:
      - "80:80"

  dashboard-database:
    container_name: database

    build:
      context: .
      dockerfile: Dockerfile_dashboard-database

    restart: always

    env_file:
      - .env

    networks:
      - dashboard

    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    command: --wait_timeout=3600

    ports:
        - "3306:3306"

networks:
  dashboard:
    name: connect
    driver: bridge
    external: true
